ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('frontend.urls',namespace='frontend')),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)



ecom/frontend/urls.py
from django.urls import path

from .views import (
    IndexPage,CategoriesPage,
    CheckOutPage, ContactPage,
    ProductPage, ShoppingCart,
    RegisterClient,login_client,
    CartCreatorView,PostCommentView,
    CartRemoverView, Odr
    )

app_name = 'frontend'

urlpatterns = [
    path('', IndexPage.as_view(),name='index'),
    path('index/', IndexPage.as_view(),name='index'),
    path('categories/',CategoriesPage.as_view(),name='categories'),
    path('checkout/',Odr.as_view(),name='checkout'),
    path('contact/',ContactPage.as_view(),name='contact'),
    path('products/<int:pk>/',PostCommentView.as_view(),name='products'),
    path('cart/',ShoppingCart.as_view(),name='cart'),
    path('cart/<int:pk>/',CartRemoverView.as_view(),name='removeCart'),
    path('register/',RegisterClient.as_view(),name='register'),
    path('login/',login_client,name='login')
]

ecom/frontend/models.py
from django.db import models

# Create your models here.
class ClientRegister(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField()
    password = models.CharField(max_length=150)

class ClientLogin(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length=150)

class CartCreator(models.Model):
    product_id = models.CharField(max_length=150)
    client_id = models.CharField(max_length=150)
    total_price = models.IntegerField(max_length=150)
    product_count = models.CharField(max_length=20)


class OrderProduct(models.Model):
    client_id = models.CharField(max_length=150)
    payable_amount = models.CharField(max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField()
    checked_by = models.CharField(max_length=150,null=True)



ecom/frontend/forms.py
from django import forms
from django.forms import ModelForm

from .models import ClientRegister, ClientLogin, CartCreator, OrderProduct

#create your forms here
class ClientRegisterForm(ModelForm):
    class Meta:
        model = ClientRegister
        fields = ['first_name','last_name','email','password']
        widgets={
            'first_name' : forms.TextInput(attrs={'placeholder': 'firstname'}),
            'last_name': forms.TextInput(attrs={'placeholder':'lastname'}),
            'email' : forms.TextInput(attrs={'placeholder': 'e@gmail.com'}),
            'password' : forms.PasswordInput(attrs={'placeholder': 'Password from numbers and letters of the Latin alphabet'})
        }
        labels = {
        'first_name': '',
        'last_name' : '',
        'email': '',
        'password': ''
        }

class ClientLoginForm(ModelForm):
    class Meta:
        model = ClientLogin
        fields = ['email','password']
        widgets = {
            'email' : forms.TextInput(attrs={'placeholder' :'Email Input'}),
            'password' : forms.PasswordInput(attrs={'placeholder' : 'Input Password'})
        }
        label = {
            'email' : '',
            'password' : ''
        }

class CartCreatorForm(ModelForm):
    product_count = forms.CharField(initial=1) 
    class Meta:
        model = CartCreator
        fields = ['product_count']
        label = {
            'product_count' : ''
        }


class OrderProductForm(ModelForm):
    class Meta:
        model = OrderProduct
        fields = ['first_name','last_name','email']
        labels = {
        'first_name': '',
        'last_name' : '',
        'email': '',
        }
        widgets={
            'first_name' : forms.TextInput(attrs={'placeholder': 'firstname'}),
            'last_name': forms.TextInput(attrs={'placeholder':'lastname'}),
            'email' : forms.TextInput(attrs={'placeholder': 'e@gmail.com'}),
        }

ecom/frontend/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView, CreateView, ListView, DetailView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import hashers
from django.views import View
from django.db.models import Avg, Count, Min, Sum

from .models import ClientRegister, ClientLogin, CartCreator, OrderProduct
from .forms import ClientRegisterForm, ClientLoginForm, CartCreatorForm, OrderProductForm

from accounts.models import AddProductModel

# Create your views here.
class IndexPage(TemplateView):
    template_name = 'frontend/index.html'

class CategoriesPage(ListView):
    model = AddProductModel
    template_name = 'frontend/categories.html'
    context_object_name = 'product_data'

class CheckOutPage(ListView):
    model = CartCreator
    template_name = 'frontend/check-out.html'
    context_object_name = 'cart_info'
  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderProductForm()  
        context['total'] =  CartCreator.objects.filter(client_id=self.request.session['client_id']).aggregate(Sum('total_price'))
        return context

class OrderComplete(CreateView):
    model = OrderProduct
    form_class = OrderProductForm
    template_name = 'frontend/check-out.html'
  
    def form_valid(self,form):
        total = CartCreator.objects.filter(client_id=self.request.session['client_id']).aggregate(Sum('total_price'))
        order = form.save(commit=False)
        order.client_id = self.request.session['client_id']
        order.payable_amount = total['total_price__sum']
        order.save()
        objects = CartCreator.objects.filter(client_id=self.request.session['client_id'])
        objects.delete()
        return redirect('frontend:categories')


class ContactPage(TemplateView):
    template_name = 'frontend/contact.html'

class ProductPage(DetailView):
    model = AddProductModel
    template_name = 'frontend/product-page.html'
    context_object_name = 'product_data'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CartCreatorForm()
        return context

class ShoppingCart(ListView):
    model = CartCreator
    template_name = 'frontend/shopping-cart.html'
    context_object_name = 'cart_data'

class RegisterClient(CreateView):
    model = ClientRegister
    form_class = ClientRegisterForm
    template_name = 'frontend/register.html'

    def form_valid(self,form):
        print(form.data)
        print(form.cleaned_data['password'])
        client = form.save(commit=False)
        client.password = form.cleaned_data['password'] #correct way of manipulation of form data
        print(form.data)
        client.save()
        return redirect('frontend:login')


def login_client(request):
    if request.method == 'POST':
        form = ClientLoginForm(request.POST)
        print(form.data)
        email = form.data['email']
        password = form.data['password']
        clientData = ClientRegister.objects.get(email=email)
        if form.is_valid():
            if password == clientData.password and email == clientData.email:
                request.session['email'] = email
                request.session['client_id'] = clientData.id
                return redirect('frontend:index')
            else:
                print('Error fucking error')
    elif request.method == 'GET':
        form = ClientLoginForm()
    return render(request,'frontend/login.html',{'form':form})


class CartCreatorView(CreateView):
    model = CartCreator
    form_class = CartCreatorForm
    template_name = 'frontend/product-page.html'
    success_url = reverse_lazy('frontend:categories')

    def form_valid(self,form):
        cart_data = form.save(commit=False)
        cart_data.product_id =  self.kwargs['pk']
        cart_data.client_id = self.request.session['client_id']

        product_info = AddProductModel.objects.get(id=cart_data.product_id)
        cart_data.total_price = int(cart_data.product_count) * int(product_info.price)

        print(cart_data.product_count) #gives number of products
        print(cart_data.product_id) #gives id of product 
        print(cart_data.client_id) #gives id of client
        print(cart_data.total_price) #gives total price 

        cart_data.save()
        return super(CartCreatorView, self).form_valid(form)


class PostCommentView(View):
    def get(self, request, *args, **kwargs):
         view = ProductPage.as_view()
         return view(request, *args, **kwargs) 

    def post(self, request, *args, **kwargs) :
         view = CartCreatorView.as_view()
         return view(request, *args, **kwargs) 


class CartRemoverView(DeleteView):
    model = CartCreator
    success_url = reverse_lazy('frontend:cart')

class Odr(View):
    def get(self, request, *args, **kwargs):
         view = CheckOutPage.as_view()
         return view(request, *args, **kwargs) 

    def post(self, request, *args, **kwargs) :
         view = OrderComplete.as_view()
         return view(request, *args, **kwargs) 



        









    

ecom/frontend/templates/frontend/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

ecom/frontend/templates/frontend/shopping-cart.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Yoga Studio Template">
    <meta name="keywords" content="Yoga, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Violet | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900&display=swap"
        rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %} " type="text/css">
    <link rel="stylesheet" href=" {% static 'css/font-awesome.min.css' %} " type="text/css">
    <link rel="stylesheet" href=" {% static 'css/nice-select.css' %} " type="text/css">
    <link rel="stylesheet" href=" {% static 'css/owl.carousel.min.css' %} " type="text/css">
    <link rel="stylesheet" href=" {% static 'css/magnific-popup.css' %} " type="text/css">
    <link rel="stylesheet" href=" {% static 'css/slicknav.min.css' %} " type="text/css">
    <link rel="stylesheet" href=" {% static 'css/style.css' %} " type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    
    <!-- Search model -->
	<div class="search-model">
		<div class="h-100 d-flex align-items-center justify-content-center">
			<div class="search-close-switch">+</div>
			<form class="search-model-form">
				<input type="text" id="search-input" placeholder="Search here.....">
			</form>
		</div>
	</div>
	<!-- Search model end -->

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="container-fluid">
            <div class="inner-header">
                <div class="logo">
                    <a href=" {% url 'frontend:index' %} "><img src=" {% static 'img/logo.png' %} " alt=""></a>
                </div>
                <div class="header-right">
                    <img src=" {% static 'img/icons/search.png' %} " alt="" class="search-trigger">
                    <img src=" {% static 'img/icons/man.png' %} " alt="">
                    <a href="#">
                        <img src=" {% static 'img/icons/bag.png' %} " alt="">
                        <span>2</span>
                    </a>
                </div>
                <div class="user-access">
                    <a href="{% url 'frontend:register' %}">Register</a>
                    <a href="{% url 'frontend:login' %}" class="in">Sign in</a>
                </div>
                <nav class="main-menu mobile-menu">
                    <ul>
                        <li><a class="active" href=" {% url 'frontend:index' %} ">Home</a></li>
                        <li><a href="  {% url 'frontend:categories' %} "> Products </a></li>
                        <li><a href="  {% url 'frontend:contact' %}  ">Contact</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <!-- Header Info Begin -->
    <div class="header-info">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4">
                    <div class="header-item">
                        <img src=" {% static 'img/icons/delivery.png' %} " alt="">
                        <p>Free shipping on orders over $30 in USA</p>
                    </div>
                </div>
                <div class="col-md-4 text-left text-lg-center">
                    <div class="header-item">
                        <img src=" {% static 'img/icons/voucher.png' %} " alt="">
                        <p>20% Student Discount</p>
                    </div>
                </div>
                <div class="col-md-4 text-left text-xl-right">
                    <div class="header-item">
                    <img src=" {% static 'img/icons/sales.png' %} " alt="">
                    <p>30% off on dresses. Use code: 30OFF</p>
                </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header Info End -->
    <!-- Header End -->

    <!-- Page Add Section Begin -->
    <section class="page-add cart-page-add">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="page-breadcrumb">
                        <h2>Cart<span>.</span></h2>
                        <a href="#">Home</a>
                        <a href="#">Dresses</a>
                        <a class="active" href="#">Night Dresses</a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <img src=" {% static 'img/add.jpg' %} " alt="">
                </div>
            </div>
        </div>
    </section>
    <!-- Page Add Section End -->

    <!-- Cart Page Section Begin -->
    <div class="cart-page">
        <div class="container">
            <div class="cart-table">
                <table>
                    <thead>
                        <tr>
                            <th class="product-h">Product</th>
                            <th class="quan">Total</th>
                            <th> Action</th>
                        </tr>
                    </thead>
                    <tbody>       
                            {% for data in cart_data %}
                                {% if data.client_id|slugify == request.session.client_id|slugify %}
                                <tr>
                                <td class="product-col">
                                        <div class="p-title">
                                            <h5> {{ data.product_id }}</h5>
                                        </div>
                                    </td>
                                    <td class="total">$ {{data.total_price}}</td>
                                    <form action="{% url 'frontend:removeCart' data.id %}" method="POST">
                                        {% csrf_token %}
                                        <td><button type="submit" onclick="return confirm('Do You want to delete ?')">X</button></td>
                                     </form>
                                </tr>
                                {% endif %}
                            {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="shopping-method">
            <div class="container">
                        <div class="total-info">
                            <div class="row">
                                <div class="col-lg-12 text-right">
                                    <a href="{% url 'frontend:checkout' %}" class="primary-btn chechout-btn">Proceed to checkout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart Page Section End -->

    <!-- Footer Section Begin -->
    <footer class="footer-section spad">
        <div class="container">
            <div class="newslatter-form">
                <div class="row">
                    <div class="col-lg-12">
                        <form action="#">
                            <input type="text" placeholder="Your email address">
                            <button type="submit">Subscribe to our newsletter</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="footer-widget">
                <div class="row">
                    <div class="col-lg-3 col-sm-6">
                        <div class="single-footer-widget">
                            <h4>About us</h4>
                            <ul>
                                <li>About Us</li>
                                <li>Community</li>
                                <li>Jobs</li>
                                <li>Shipping</li>
                                <li>Contact Us</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="single-footer-widget">
                            <h4>Customer Care</h4>
                            <ul>
                                <li>Search</li>
                                <li>Privacy Policy</li>
                                <li>2019 Lookbook</li>
                                <li>Shipping & Delivery</li>
                                <li>Gallery</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="single-footer-widget">
                            <h4>Our Services</h4>
                            <ul>
                                <li>Free Shipping</li>
                                <li>Free Returnes</li>
                                <li>Our Franchising</li>
                                <li>Terms and conditions</li>
                                <li>Privacy Policy</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="single-footer-widget">
                            <h4>Information</h4>
                            <ul>
                                <li>Payment methods</li>
                                <li>Times and shipping costs</li>
                                <li>Product Returns</li>
                                <li>Shipping methods</li>
                                <li>Conformity of the products</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="social-links-warp">
			<div class="container">
				<div class="social-links">
					<a href=" {% static '' %} " class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
					<a href=" {% static '' %} " class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
					<a href=" {% static '' %} " class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
					<a href=" {% static '' %} " class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
					<a href=" {% static '' %} " class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
					<a href=" {% static '' %} " class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
				</div>
			</div>


            <div class="container text-center pt-5">
                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>



		</div>
    </footer>
    <!-- Footer Section End -->

    <!-- Js Plugins -->
    <script src=" {% static 'js/jquery-3.3.1.min.js' %} "></script>
    <script src=" {% static 'js/bootstrap.min.js' %} "></script>
    <script src=" {% static 'js/jquery.magnific-popup.min.js' %} "></script>
    <script src=" {% static 'js/jquery.slicknav.js' %} "></script>
    <script src=" {% static 'js/owl.carousel.min.js' %} "></script>
    <script src=" {% static 'js/jquery.nice-select.min.js' %} "></script>
    <script src=" {% static 'js/mixitup.min.js' %} "></script>
    <script src=" {% static 'js/main.js' %} "></script>
</body>

</html>