ecom/accounts/urls.py
from django.urls import path

from .views import (
    AddAdminView, HomePageView,
    login_view, AdminLogoutView, 
    AdminsList, UpdateAdmin,DeleteAdmin,
    AddProduct, ProductView, UpdateProduct,
    DeleteProduct, UpdateOder, OrderView
    )

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view,name="login"),
    path('logout/', AdminLogoutView.as_view(),name="logout"),
    path('addProduct/', AddProduct.as_view(),name="addProduct"),
    path('viewOrder/', OrderView.as_view(),name="viewOrder"),
    
    path('updateOrder/<int:pk>/', UpdateOder.as_view(),name="updateOrder"),

    path('updateProduct/<int:pk>/', UpdateProduct.as_view(),name="updateProduct"),
    path('deleteProduct/<int:pk>/', DeleteProduct.as_view(),name="deleteProduct"),
    path('viewProduct/', ProductView.as_view(),name="viewProduct"),
    path('list/', AdminsList.as_view(),name="list"),
    path('register/', AddAdminView.as_view(),name="register"),
    path('update/<int:pk>/', UpdateAdmin.as_view(),name="update"),
    path('delete/<int:pk>/', DeleteAdmin.as_view(),name="delete"),
    path('homepage/', HomePageView.as_view(),name="homepage"),
]

ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('frontend.urls',namespace='frontend')),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)



ecom/accounts/models.py
from django.db import models
# import os
# from uuid import uuid4

# def rename(path):
#     def wrapper(instance, filename):
#         ext = filename.split('.')[-1]
#         # get filename
#         if instance.pk:
#             filename = '{}.{}'.format(instance.pk, ext)
#         else:
#             # set filename as random string
#             filename = '{}.{}'.format(uuid4().hex, ext)
#         # return the whole path to the file
#         return os.path.join(path, filename)
#     return wrapper

# Create your models here.
class AddProductModel(models.Model):
    product_name = models.CharField(max_length=150)
    product_description = models.TextField(max_length=150)
    price = models.CharField(max_length=150)
    #product_image = models.FileField(upload_to=rename('documents/'))
    product_image = models.FileField(upload_to='documents/') #needs to be commented out and the commented one shall be used
    product_added_by = models.CharField(max_length=150,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

ecom/accounts/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.forms import ModelForm
from .models import AddProductModel

USER = get_user_model()


class AdminAddForm(ModelForm):
    class Meta:
        model = USER
        fields = ['first_name','last_name','username','password']
        widgets = {
            'password' : forms.PasswordInput()
        }

#create using forms.Form
class AdminLoginFrom(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150,widget=forms.PasswordInput())


class AddProductForm(ModelForm):
    class Meta:
        model = AddProductModel
        fields = ['product_name','product_description','product_image','price']
        widgets={
            'product_name' : forms.TextInput(attrs={'placeholder': 'name'}),
            'product_description': forms.TextInput(attrs={'placeholder':'description'})
        }

    

ecom/accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView,CreateView, ListView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView, LogoutView
from django.views import View
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login, logout
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from .forms import AdminAddForm, AdminLoginFrom, AddProductForm
from .models import AddProductModel

from frontend.models import OrderProduct
from frontend.forms import OrderProductForm

USER = get_user_model()


# Create your views here. Admin Operations Starts From Here
class AddAdminView(CreateView):
    def get(self,request,*args,**kwargs):
        form = AdminAddForm()
        return render(request, 'accounts/register.html',{ 'form': form })

    def post(self,request,*args,**kwargs):
        form = AdminAddForm(request.POST)
        if form.is_valid():
            print('form is clean')
            print(form.cleaned_data)
            user = USER(
                first_name = form.cleaned_data['first_name'],
                last_name = form.cleaned_data['last_name'],
                username = form.cleaned_data['username'],
                password = form.cleaned_data['password'],
                )    
            user.save()
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('/accounts/login/')
        else:
            return render(request, 'accounts/register.html',{ 'form': form })

@method_decorator(login_required,name='dispatch')
class HomePageView(TemplateView):
    template_name = 'accounts/homepage.html'

#soultion dont use modelform in this use form.form in this very matter
def login_view(request):
    if request.method == 'POST':
        form = AdminLoginFrom(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password']
                )
            if user:
                login(request,user)
                return redirect('/accounts/homepage/')
            else:
                print('Username or password doesnot exitst')
    elif request.method == 'GET':
        form = AdminLoginFrom()
    return render(request,'accounts/login.html',{'form':form})

#creating logout view
class AdminLogoutView(LogoutView):
    next_page = '/accounts/login/'

@method_decorator(login_required, name='dispatch')
class AdminsList(ListView):
    model = USER
    template_name = 'accounts/adminList.html'
    context_object_name = 'admin_data'

@method_decorator(login_required,name='dispatch')
class UpdateAdmin(UpdateView):
    model = USER
    template_name = 'accounts/update.html'
    form_class = AdminAddForm
    context_object_name = 'admin_data'
    success_url = reverse_lazy('accounts:list')

@method_decorator(login_required,name='dispatch')
class DeleteAdmin(DeleteView):
    model = USER
    success_url = reverse_lazy('accounts:list')

###Products Operation Starts From Here
@method_decorator(login_required,name='dispatch')
class AddProduct(CreateView):
    model = AddProductModel
    form_class = AddProductForm
    template_name = 'accounts/addProduct.html'

    def form_valid(self,form):
        product = form.save(commit=False)
        product.product_added_by = self.request.user
        product.save()
        return redirect('/accounts/viewProduct/')


@method_decorator(login_required, name='dispatch')
class ProductView(ListView):
    model = AddProductModel
    template_name = 'accounts/viewProduct.html'
    context_object_name = 'product_data'

@method_decorator(login_required,name='dispatch')
class UpdateProduct(UpdateView):
    model = AddProductModel
    template_name = 'accounts/editProduct.html'
    form_class = AddProductForm
    success_url = reverse_lazy('accounts:viewProduct')

@method_decorator(login_required,name='dispatch')
class DeleteProduct(DeleteView):
    model = AddProductModel
    success_url = reverse_lazy('accounts:viewProduct')

@method_decorator(login_required, name='dispatch')
class OrderView(ListView):
    model = OrderProduct
    template_name = 'accounts/viewOrders.html'
    context_object_name = 'order_data'

@method_decorator(login_required,name='dispatch')
class UpdateOder(UpdateView):
    model = OrderProduct
    form_class = OrderProductForm
    template_name = 'accounts/editOrders.html'
    success_url = reverse_lazy('accounts:viewOrder')

    def form_valid(self,form):
        order = form.save(commit=False)
        order.checked_by = self.request.user.first_name
        order.save()
        return redirect('/accounts/viewOrder/')







           
  
    

ecom/accounts/templates/accounts/addProduct.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block maincontent %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form | crispy }}
        <button type="submit" class="btn btn-success"> Add Product </button>
    </form>
{% endblock %}

ecom/accounts/templates/accounts/adminList.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block maincontent %}

<a href="{% url 'accounts:register' %}" class="btn btn-success"> Add Admin </a>
<br>
<br>
{% for data in admin_data %}
First Name : {{ data.first_name }}
Last Name : {{ data.last_name }}
Id : {{ data.id }}
<a href="{% url 'accounts:update' data.id %}" class="btn btn-warning"> Update Admin</a>
<form action="{% url 'accounts:delete' data.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger" onclick="return confirm('Do You want to delete ?')">Delete</button>
</form>
<hr><hr>
{% endfor %}
{% endblock %}

ecom/accounts/templates/accounts/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title> Violet Ecommerce </title>
  </head>
  <body>
    {% if user.is_authenticated %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'accounts:homepage' %}">Violet Store </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:list' %}"> View Admins</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:viewProduct' %}"> View Products </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#"> View Orders </a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="#"> View Queries </a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="#"> View Client Details </a>
              </li>
            </ul>
          </div>
        </nav>
    {% endif %}
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-8">
          {% block maincontent %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>


ecom/accounts/templates/accounts/editOrders.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block maincontent %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form | crispy }}
        <button type="submit" class="btn btn-success"> Mark As Checked </button>
    </form>
{% endblock %}

ecom/accounts/templates/accounts/editProduct.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block maincontent %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form | crispy }}
        <button type="submit" class="btn btn-success"> Add Product </button>
    </form>
{% endblock %}

ecom/accounts/templates/accounts/homepage.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block maincontent %}
  <h1> Hey Mofo I am from Homepage</h1>
    {% if user.is_authenticated %}
        <p>Welcome, {{ user.get_username }}. Thanks for logging in. <a href="/accounts/logout/"> Logout </a></p>
    {% else %}
        <p>Welcome, new user. Please log in. <a href="/accounts/login/"> Login </a></p>
    {% endif %}
{% endblock %}

ecom/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block maincontent %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form | crispy }}
        <button type="submit" class="btn btn-success"> Login </button>
    </form>
{% endblock %}

ecom/accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block maincontent %}
   <form action="" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-success"> Add </button>
   </form>
{% endblock%}

ecom/accounts/templates/accounts/update.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block maincontent %}
   <form action="" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-success"> Add </button>
   </form>
{% endblock%}

ecom/accounts/templates/accounts/viewOrders.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block maincontent %}
<br>
<br>
{% for data in order_data %}
Amount Payable : {{ data.payable_amount }}
client_id : {{ data.client_id }}
First Name : {{ data.first_name }}
Last Name : {{ data.last_name }}
checked_by : {{ data.checked_by }}
Email  : {{ data.email }}

<a href="{% url 'accounts:updateOrder' data.id %}" class="btn btn-warning"> Check For Validity </a>
<hr><hr>
{% endfor %}
{% endblock %}

ecom/accounts/templates/accounts/viewProduct.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block maincontent %}

<a href="{% url 'accounts:addProduct' %}" class="btn btn-success"> Add Product </a>
<br>
<br>
{% for data in product_data %}
Product Name : {{ data.product_name }}
Product Price : {{ data.price }}
Product Desc : {{ data.product_description }}
<img src="/media/{{ data.product_image }}" alt="image" height="100px" width="100px">
Created By : {{ data.product_added_by }}
Created At : {{ data.created_at }}

<a href="{% url 'accounts:updateProduct' data.id %}" class="btn btn-warning">Update</a>
<form action="{% url 'accounts:deleteProduct' data.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger" onclick="return confirm('Do You want to delete ?')">Delete</button>
</form>
<hr><hr>
{% endfor %}
{% endblock %}